# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Appknox
email: sunny@appknox.com
description: > # this means to ignore newlines until "baseurl:"
  Appknox detects & addresses vulnerabilities in mobile apps enabling businesses achieve faster time to market higher productivity 360° mobile security
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.appknox.com" # the base hostname & protocol for your site
twitter_username: appknox
github_username:  appknox

# Build settings
markdown: kramdown

# Exclude Files
exclude:
  - Rakefile
  - README.md
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - .editorconfig
  - deploy.sh
  - .eslintrc
  - .gitignore
  - .jsbeautifyrc
  - .jshintignore
  - deploy_github.sh
