# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Appknox
email: sunny@appknox.com
description: > # this means to ignore newlines until "baseurl:"
  Appknox detects & addresses vulnerabilities in mobile apps enabling businesses achieve faster time to market higher productivity 360° mobile security
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.appknox.com" # the base hostname & protocol for your site
twitter_username: appknox
github_username:  appknox

# Gem option
gems:
  - jekyll-multiple-languages-plugin
  - jekyll-assets

# Available languages
languages: ["en", "in"]

# Exclude options
exclude_from_localizations: ["js", "img", "css"]

# Build settings
markdown: kramdown

# Exclude Files
exclude:
  - Rakefile
  - README.md
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - .editorconfig
  - deploy.sh
  - .eslintrc
  - .gitignore
  - .jsbeautifyrc
  - .jshintignore
  - deploy_github.sh
  - s3_website.yml
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md

assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: false
  cache_type: memory
  cdn: https://www.appknox.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "bundle.css"
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    liquid: true
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true
